### ISSUE TITLE
User selection menu slows down after resizing window

### ISSUE THREAD

**Issue by tbressler** [tbressler/waterrower-workout#1]
The user selection menu slows down when resizing the window of the application and the connecting animation is running.

Reproduce:
1. Start application
2. Do not connect WaterRower, so that connecting animation is running
3. Resize window multiple times
4. Click on select user button

Result:
The select user menu is very slow.

**Comment by tbressler** [comment]
Found possible root cause:
https://bugs.openjdk.java.net/browse/JDK-8088857

**Comment by tbressler** [comment]
Additionally several exceptions can be found:

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.sun.javafx.tk.quantum.WindowStage.setBounds(WindowStage.java:285)
	at javafx.stage.Window$TKBoundsConfigurator.apply(Window.java:1274)
	at javafx.stage.Window$TKBoundsConfigurator.pulse(Window.java:1290)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$29(Toolkit.java:398)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:397)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:421)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$403(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$147(WinApplication.java:177)
	at java.lang.Thread.run(Thread.java:748)
```
